Repository tofu-tf/derevo, pull requests merged in 2020-01, with the labels that each got.

#74 Circe scala doc.
  circe/src/main/scala/derevo/circe/circe.scala
Labels: docs

#55 Add doc for scalacheck module
  README.md
  scalacheck/src/test/scala/derevo/scalacheck/ArbitrarySpec.scala
Labels: docs

#77 Update magnolia to 0.12.6
  project/Version.scala
Labels: chore

#78 Update reactivemongo-bson-macros to 0.20.1
  project/Version.scala
Labels: chore

#72 Add solution for #27
  core/src/main/scala/derevo/Derevo.scala
Labels: bug, enhancement

#80 Update cats-tagless-core, ... to 0.11
  project/Version.scala
Labels: chore

#79 Update sbt to 1.3.7
  project/build.properties
Labels: chore

#81 Update reactivemongo-bson-macros to 0.20.2
  project/Version.scala
Labels: chore

#82 Add solution for #27
  core/src/main/scala/derevo/Derevo.scala
Labels: enhancement

#83 Update magnolia to 0.12.6
  project/Version.scala
Labels: chore

#84 Update kind-projector to 0.11.0
  build.sbt
Labels: chore

#85 Update Scalacheck doc
  README.md
  scalacheck/src/test/scala/derevo/scalacheck/ArbitrarySpec.scala
Labels: docs

#86 Implement IntelliJ Integration
  .gitignore
  README.md
  intellij/build.gradle
  intellij/gradle/wrapper/gradle-wrapper.jar
  intellij/gradle/wrapper/gradle-wrapper.properties
  intellij/gradlew
  intellij/gradlew.bat
  intellij/settings.gradle
  intellij/src/main/resources/META-INF/plugin.xml
  intellij/src/main/scala/derevo/intellij/synthetic/macros/CatsFinalAlgInjector.scala
  intellij/src/main/scala/derevo/intellij/synthetic/macros/DerevoDeriveInjector.scala
Labels: enhancement

#69 New derevo "Circe Magnolia"
  README.md
  build.sbt
  circeMagnolia/build.sbt
  circeMagnolia/src/main/scala/derevo/circe/magnolia/circe.scala
  circeMagnolia/src/test/scala/derevo/circe/magnolia/CirceDerivationSpec.scala
  project/Version.scala
  scalacheck/src/test/scala/derevo/scalacheck/ArbitrarySpec.scala
Labels: enhancement

#87 Update derevo-intellij README and meta info
  README.md
  intellij/build.gradle
  intellij/src/main/resources/META-INF/plugin.xml
Labels: docs

#88 Update ciris to 1.0.4
  project/Version.scala
Labels: chore
