Repository tofu-tf/derevo, pull requests merged in 2021-06, with the labels that each got.

#285 Update sbt to 1.5.3
  project/build.properties
Labels: chore

#293 Fix build
  .github/workflows/ci.yml
  README.md
  ci-release.sbt
Labels: skip-changelog

#295 Update circe-derivation to 0.13.0-M5
  project/Dependencies.scala
Labels: dependency-update

#294 Update pureconfig to 0.16.0
  project/Dependencies.scala
Labels: dependency-update
